name: weather_alert_pakistan
description: Weather & Prayer Alert PK - Weather forecasts and Islamic prayer times
publish_to: 'none'

version: 1.1.21+22

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  geolocator: ^12.0.0
  webview_flutter: ^4.8.0
  collection: ^1.18.0 
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.3
  cloud_firestore: ^6.1.0
  adhan: ^2.0.0+1
  timezone: ^0.10.1
  home_widget: ^0.8.1
  google_maps_flutter: ^2.5.3
  device_info_plus: ^12.3.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/